### ISSUE TITLE
Closing Zeroconf object blocks while joining engine thread

### ISSUE THREAD

**Issue by smcv** [jstasiak/python-zeroconf#126] opened 2018-04-04 11:47 UTC
To reproduce: Paste the example from README.rst into a file and run it:

    from zeroconf import ServiceBrowser, Zeroconf

    class MyListener:

        def remove_service(self, zeroconf, type, name):
            print("Service %s removed" % (name,))

        def add_service(self, zeroconf, type, name):
            info = zeroconf.get_service_info(type, name)
            print("Service %s added, service info: %s" % (name, info))

    zeroconf = Zeroconf()
    listener = MyListener()
    browser = ServiceBrowser(zeroconf, "_http._tcp.local.", listener)
    try:
        input("Press enter to exit...\n\n")
    finally:
        zeroconf.close()

Expected result: Script displays a line for a networked printer on my local LAN. I press Enter and the script exits.

Actual result: Pressing Enter has no visible effect. Enter followed by ^C produces this:

```
Press enter to exit...

Service HP Color LaserJet [etc.] added, [etc.]

^CTraceback (most recent call last):
  File "t.py", line 22, in <module>
    zeroconf.close()
  File ".../python-zeroconf/zeroconf.py", line 2066, in close
    self.engine.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by jstasiak** [comment] 2018-04-04 12:55
Unfortunately I can't reproduce this.

**Comment by smcv** [comment] 2018-04-04 22:29
If it matters, I'm using Python 3.6.5 from Debian unstable, and I get the same behaviour with both the upstream zeroconf.py from this git repository, and the older python-zeroconf from Debian.

**Comment by bdraco** [comment] 2021-06-22 00:52
This is fixed on master

**Closed by bdraco** 2021-06-22 00:52 UTC
