### ISSUE TITLE
Dependency netifaces installation error on Python3

### ISSUE THREAD

**Issue by SpotlightKid** [jstasiak/python-zeroconf#31] opened 2015-11-06 00:29 UTC
ATM, you can't install `zeroconf` from PyPI via pip on Python 3, because the `setup.py` of the package `netifaces`, which is a dependency of `zeroconf` i broken:

https://bitbucket.org/al45tair/netifaces/issues/13/0104-install-is-broken-on-python-3x

Please consider switching the dependency to [gns3-netifaces](https://pypi.python.org/pypi/gns3-netifaces) and release a new version of `zeroconf` on PyPI, until `netifaces` is fixed.

**Comment by jstasiak** [comment] 2015-12-01 00:43
Thank you for the note @SpotlightKid, I decided to switch to psutil. Could you test the current master and confirm whether it works for you?

**Comment by SpotlightKid** [comment] 2015-12-01 01:32
Looks good.

Although psutil is a rather heavy dependency for "just" getting a list of network interfaces. But as long as it works on a Raspberry Pi that's ok for me.

**Comment by jstasiak** [comment] 2015-12-01 08:54
I think the deciding factor here is that psutil doesn't seem to work on pypy3 and I'd like to keep the pypy3 support - I'll have a look at using that fork.

**Comment by jstasiak** [comment] 2015-12-01 09:06
@SpotlightKid I just remembers that this project's CI process includes Python 3 builds and there doesn't seem to be any problem with those and ``netifaces`` seems just fine[1]. Does it actually fail for you? If so - what is the error message?


[1] https://travis-ci.org/jstasiak/python-zeroconf/jobs/94120748

**Comment by SpotlightKid** [comment] 2015-12-01 13:57
It was the error in the travis log linked in the netifaces issue I referenced. But I don''t get the error anymore as well. It seems it was maybe related to pips sandbox execution environment for the `setup.py`, since netifaces' `setup.py` [accesses](https://bitbucket.org/al45tair/netifaces/src/b18f5006166db6e06753465f341f5fd9d85222ea/setup.py?at=default&fileviewer=file-view-default#setup.py-23) the `builtins`  module. Maybe previous pip versions did not support that?

**Comment by jstasiak** [comment] 2016-03-14 20:57
I'll close this issue as the problem is not reproducible with modern environments, please reopen if the issue reappears. Thanks for the report.

**Closed by jstasiak** 2016-03-14 20:57 UTC
