### ISSUE TITLE
ImportError with zeroconf 0

### ISSUE THREAD

**Issue by nicolargo** [jstasiak/python-zeroconf#21] opened 2015-04-27 10:09 UTC
On my CentOS 7 configuration with Zeroconf 0.17.1 and Six 1.9.0:

```
± ipython
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import zeroconf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c556a850dc86> in <module>()
----> 1 import zeroconf

/usr/lib/python2.7/site-packages/zeroconf.py in <module>()
     34 
     35 import netifaces
---> 36 from six import binary_type, indexbytes, int2byte, iteritems, text_type
     37 from six.moves import xrange
     38 

ImportError: cannot import name indexbytes
```

**Comment by jstasiak** [comment] 2015-04-27 20:50
Hey! From my experience it's caused by ``six.pyc`` bytecode file generated from old six version left in the filesystem in ``PYTHONPATH`` somewhere.

Could you run those two commands and paste the results? This should make everything clear.

```
python -c "import six; print(six.__file__, six.__version__)"
grep -n indexbytes `python -c "import six; print(six.__file__.replace('.pyc', '.py'))"`
```

**Comment by jstasiak** [comment] 2015-07-10 10:32
I'm closing this due to no feedback, please feel free to reopen.

**Closed by jstasiak** 2015-07-10 10:32 UTC
